# https://serokell.io/posts/2018-01-24-using-travis-CI-for-Haskell-projects.html
# also see:
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
# https://docs.haskellstack.org/en/stable/travis_ci/
# https://github.com/commercialhaskell/stack/blob/master/.travis.yml
# https://github.com/ekmett/intervals/blob/master/.travis.yml

sudo: false

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/build/tonyday567/numhask/.stack-work

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.2    # required by GHC 8.*
      - cabal-install-head    # required by GHC head

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --haddock --no-haddock-deps
