resolver: lts-13.20

packages:
  - ../numhask
  - ../numhask-prelude
  - ../numhask-array
  - ../numhask-hedgehog
  # issues with hmatrix
  - .
  - ../numhask-space

extra-deps:
  - dimensions-1.0.1.1
  - perf-0.4.1.0
  - perf-analysis-0.0.1.1
  - rdtsc-1.3.0.1

